use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.

config :absolventenfeier, Absolventenfeier.Repo,
  ssl: true,
  adapter: Ecto.Adapters.Postgres,
  pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10")

config :absolventenfeier, AbsolventenfeierWeb.Endpoint,
  load_from_system_env: true,
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true

config :absolventenfeier, Absolventenfeier.Mailer,
  adapter: Bamboo.SMTPAdapter,
  server: {:system, "SMTP_HOST"},
  hostname: {:system, "HOST"},
  port: {:system, "SMTP_PORT"},
  username: {:system, "SMTP_USERNAME"},
  password: {:system, "SMTP_PASSWORD"},
  ssl: true,
  tls: :always,
  auth: :always

# Do not print debug messages in production
config :logger, level: :info
