use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.

database_url =
  System.get_env("DATABASE_URL") ||
    raise """
    environment variable DATABASE_URL is missing.
    For example: ecto://USER:PASS@HOST/DATABASE
    """

config :aion, Absolventenfeier.Repo,
  ssl: true,
  url: database_url,
  adapter: Ecto.Adapters.Postgres,
  pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10")

secret_key_base =
  System.get_env("SECRET_KEY_BASE") ||
    raise """
    environment variable SECRET_KEY_BASE is missing.
    You can generate one by calling: mix phx.gen.secret
    """

live_view_signing_salt =
  System.get_env("LIVE_VIEW_SIGNING_SALT") ||
    raise("expected the LIVE_VIEW_SIGNING_SALT environment variable to be set")

host =
  System.get_env("HOST") ||
    raise """
    environment variable HOST is missing.
    """

config :absolventenfeier, AbsolventenfeierWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true,
  http: [
    port: String.to_integer(System.get_env("PORT") || "4000"),
    transport_options: [socket_opts: [:inet6]]
  ],
  url: [
    host: host,
    port: 443
  ],
  secret_key_base: secret_key_base,
  live_view: [signing_salt: live_view_signing_salt]

smtp_host =
  System.get_env("SMTP_HOST") ||
    raise """
    environment variable SMTP_HOST is missing.
    """

smtp_user_name =
  System.get_env("SMTP_USER_NAME") ||
    raise """
    environment variable SMTP_USER_NAME is missing.
    """

smtp_password =
  System.get_env("SMTP_PASSWORD") ||
    raise """
    environment variable SMTP_PASSWORD is missing.
    """

smtp_port =
  System.get_env("SMTP_PORT") ||
    raise """
    environment variable SMTP_PORT is missing.
    """

config :absolventenfeier, Absolventenfeier.Mailer,
  server: smtp_host,
  hostname: host,
  port: smtp_port,
  username: smtp_user_name,
  password: smtp_password,
  ssl: true,
  tls: :always,
  auth: :always

# Do not print debug messages in production
config :logger, level: :info
