use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.

config :absolventenfeier, AbsolventenfeierWeb.Endpoint,
  load_from_system_env: true,
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true

# config :absolventenfeier, Absolventenfeier.Mailer,
#   adapter: Bamboo.SMTPAdapter,
#   server: "smtp.office365.com",
#   hostname: "absolventenfeier.fachschaft-wiwi.ms",
#   port: 587,
#   username: {:system, "SMTP_USERNAME"},
#   password: {:system, "SMTP_PASSWORD"},
#   tls: :never,
#   allowed_tls_versions: [:"tlsv1", :"tlsv1.1", :"tlsv1.2"],
#   ssl: false,
#   retries: 1,
#   no_mx_lookups: false,
#   auth: :always

# Do not print debug messages in production
config :logger, level: :info
